# Generated by Django 3.2.6 on 2022-09-09 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('description', models.TextField(verbose_name='Hakkında')),
                ('image', models.ImageField(default='static/upload/author/default.jpg', upload_to='static/upload/author/%Y/%m/%d', verbose_name='Resim')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Seo Adres')),
                ('facebook', models.CharField(max_length=500, verbose_name='facebook')),
                ('twitter', models.CharField(max_length=500, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=500, verbose_name='İnstagram')),
                ('youtube', models.CharField(max_length=500, verbose_name='Youtube')),
                ('github', models.CharField(max_length=500, verbose_name='Github')),
                ('website', models.CharField(max_length=500, verbose_name='Web Site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
