# Generated by Django 3.2.6 on 2022-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Erkek'), ('FEMALE', 'Kadın')], max_length=6),
        ),
    ]
