# Generated by Django 3.2.6 on 2022-09-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
    ]
