# Generated by Django 3.2.6 on 2022-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Seo Adres'),
        ),
    ]
