# Generated by Django 3.2.6 on 2022-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220909_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='linkedin',
            field=models.CharField(max_length=500, null=True, verbose_name='linkedin'),
        ),
    ]
