# Generated by Django 3.2.6 on 2022-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220911_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cv',
            field=models.FileField(null=True, upload_to='static/upload/cv/%Y/%m/%d', verbose_name='CV Yükle'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_activate',
            field=models.BooleanField(default=False, null=True, verbose_name='Profili Görüntüle'),
        ),
    ]
