# Generated by Django 3.2.6 on 2022-09-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.TextField(null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
