# Generated by Django 3.2.6 on 2022-09-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_activate',
            field=models.IntegerField(default=0, null=True, verbose_name='Portal Durum'),
        ),
    ]
