# Generated by Django 3.2.6 on 2022-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_account_profile_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cv',
            field=models.FileField(default='static/upload/cv/default.pdf', null=True, upload_to='static/upload/cv/%Y/%m/%d', verbose_name='CV Yükle'),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.CharField(default='/', max_length=500, null=True, verbose_name='linkedin'),
        ),
    ]
