# Generated by Django 3.2.6 on 2022-10-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220916_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Kulanıcı Listesi'},
        ),
    ]
