# Generated by Django 3.2.6 on 2022-11-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20221109_1106'),
        ('users', '0018_account_rank'),
    ]

    operations = [
    ]
