# Generated by Django 3.2.6 on 2022-11-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_0016_auto_20221109_1106_0018_account_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name_plural': 'Ekipler'},
        ),
        migrations.AlterModelOptions(
            name='rankrequest',
            options={'verbose_name_plural': 'Kulanıcı Yetki Talepleri'},
        ),
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rank', verbose_name='Ekip'),
        ),
        migrations.AlterField(
            model_name='rankrequest',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Kullanıcı Adı'),
        ),
        migrations.CreateModel(
            name='RankSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rütbe Başlık', max_length=200, null=True, verbose_name='Rütbe Başlık')),
                ('description', models.CharField(default='Rütbe Açıklama', max_length=500, null=True, verbose_name='Rütbe Açıklama')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rank')),
            ],
            options={
                'verbose_name_plural': 'Rütbeler',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='rank_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ranksub', verbose_name='Rütbe'),
        ),
    ]
