# Generated by Django 3.2.6 on 2022-09-09 11:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Başlık')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Açıklama')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='static/upload/default.jpg', upload_to='static/upload/%Y/%m/%d', verbose_name='Resim(Önerilen:788x443)')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Seo Adres')),
                ('views', models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('types', models.CharField(choices=[('1', 'Video Tasarımı'), ('2', 'Haber Tasarımı'), ('3', 'Makale Tasarımı')], default='3', max_length=2, verbose_name='Tasarım Tipi')),
                ('available', models.BooleanField(default=False, verbose_name='Yayına Al')),
            ],
            options={
                'ordering': ['-created_date'],
                'permissions': [('editor_operations', 'Editör İşlemleri')],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kategori Açıklama')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='Resim Başlık')),
                ('image_description', models.CharField(max_length=300, verbose_name='Resim Açıklama')),
                ('image', models.ImageField(default='static/upload/default.jpg', upload_to='static/upload/%Y/%m/%d', verbose_name='Resim')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tür Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tür Açıklama')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta Adresi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=False, verbose_name='Onayla')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.articles', verbose_name='Blog Başlık')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='article_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.types', verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.categories', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='articles',
            name='last_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edit', to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Editör'),
        ),
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
    ]
