# Generated by Django 3.2.6 on 2021-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media/%Y/%m/%d', verbose_name='Resim'),
        ),
    ]
