# Generated by Django 3.2.6 on 2021-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles/%Y/%m/%d', verbose_name='Resim'),
        ),
    ]
