# Generated by Django 3.2.6 on 2022-09-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_likedarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedarticle',
            old_name='writer',
            new_name='user',
        ),
    ]
