# Generated by Django 3.2.6 on 2021-08-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
        ('articles', '0005_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writers.writers', verbose_name='Yazar'),
        ),
    ]
