# Generated by Django 3.2.6 on 2022-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20220910_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_type',
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Seo Adres'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='types',
            field=models.CharField(choices=[('1', 'Görsel Büyük Tasarımı'), ('2', 'Dengeli Tasarımı'), ('3', 'Text Ağırlıklı Tasarımı')], default='3', max_length=2, verbose_name='Tasarım Tipi'),
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
