# Generated by Django 3.2.6 on 2021-08-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Posta Adresi'),
        ),
    ]
