# Generated by Django 3.2.6 on 2022-09-11 14:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_auto_20220911_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Başlık')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Açıklama')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='static/upload/default.jpg', upload_to='static/upload/%Y/%m/%d', verbose_name='Resim(Önerilen:788x443)')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Seo Adres')),
                ('views', models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('types', models.CharField(choices=[('1', 'Görsel Büyük Tasarımı'), ('2', 'Dengeli Tasarımı'), ('3', 'Text Ağırlıklı Tasarımı')], default='3', max_length=2, verbose_name='Tasarım Tipi')),
                ('available', models.BooleanField(default=False, verbose_name='Yayına Al')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categories', verbose_name='Kategori')),
                ('last_edit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edit_video', to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Editör')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-created_date'],
                'permissions': [('editor_operations', 'Editör İşlemleri')],
            },
        ),
    ]
