# Generated by Django 3.2.6 on 2022-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='last_edit',
            new_name='last_edit_video',
        ),
    ]
