# Generated by Django 3.2.6 on 2021-08-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slider',
            field=models.ImageField(default='articles/slider/default.png', upload_to='articles/slider/%Y/%m/%d', verbose_name='Slider(Önerilen:788x443)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='articles/images/default.jpg', upload_to='articles/images/%Y/%m/%d', verbose_name='Resim'),
        ),
    ]
