# Generated by Django 3.2.6 on 2022-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20220911_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='table_name',
            field=models.CharField(default='makale', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='table_name',
            field=models.CharField(default='haber', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='videos',
            name='table_name',
            field=models.CharField(default='video', editable=False, max_length=20),
        ),
    ]
