# Generated by Django 3.2.6 on 2022-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20220911_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Yayına Al'),
        ),
        migrations.AlterField(
            model_name='news',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Yayına Al'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Yayına Al'),
        ),
    ]
