# Generated by Django 3.2.6 on 2021-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_articles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='Resim Başlık')),
                ('image_description', models.CharField(max_length=300, verbose_name='Resim Açıklama')),
                ('image', models.ImageField(default='articles/images/default.jpg', upload_to='articles/images/%Y/%m/%d', verbose_name='Resim')),
            ],
        ),
    ]
