# Generated by Django 3.2.6 on 2022-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20220912_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='table_name',
        ),
        migrations.AddField(
            model_name='articles',
            name='table_name',
            field=models.CharField(default='makale', editable=False, max_length=20),
        ),
    ]
