# Generated by Django 3.2.6 on 2021-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Açıklama'),
        ),
    ]
