# Generated by Django 3.2.6 on 2022-09-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20220912_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedarticle',
            name='news',
        ),
        migrations.RemoveField(
            model_name='likedarticle',
            name='video',
        ),
    ]
