# Generated by Django 3.2.6 on 2022-09-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20220912_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedarticle',
            name='article',
        ),
    ]
