# Generated by Django 3.2.6 on 2022-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_likedarticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedarticle',
            name='post',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
