# Generated by Django 3.2.6 on 2022-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_likedarticle_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_link',
            field=models.CharField(max_length=250, null=True, verbose_name='Youtube Video Adresi'),
        ),
    ]
