# Generated by Django 3.2.6 on 2022-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_readpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='readpost',
            name='user',
        ),
        migrations.AlterField(
            model_name='readpost',
            name='read_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
