# Generated by Django 3.2.6 on 2022-10-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20221025_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Başlık'),
        ),
    ]
