# Generated by Django 3.2.6 on 2022-10-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True, verbose_name='Seo Adres'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True, verbose_name='Seo Adres'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True, verbose_name='Seo Adres'),
        ),
    ]
