# Generated by Django 3.2.6 on 2022-10-29 23:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20221025_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='İçerik'),
        ),
    ]
