# Generated by Django 3.2.6 on 2022-09-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20211110_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Ad Soyad')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='E-Posta')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('available', models.BooleanField(default=False, verbose_name='Yayına Al')),
                ('last_edit_slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edit_slider', to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Editör')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
