# Generated by Django 3.2.6 on 2022-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='static/upload/default.jpg', upload_to='static/upload/slider/%Y/%m/%d', verbose_name='Resim(Önerilen:788x443)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='Url'),
        ),
    ]
