# Generated by Django 3.2.6 on 2022-09-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220915_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='available',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='last_edit_slider',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='writer',
        ),
    ]
