# Generated by Django 3.2.6 on 2022-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_slider_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'İletişim'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slaytlar'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
    ]
