# Generated by Django 3.2.6 on 2021-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('description', models.TextField(verbose_name='Hakkında')),
                ('image', models.ImageField(default='writers/images/default.jpg', upload_to='writers/images/%Y/%m/%d', verbose_name='Resim')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Seo Adres')),
                ('facebook', models.CharField(max_length=500, verbose_name='facebook')),
                ('twitter', models.CharField(max_length=500, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=500, verbose_name='İnstagram')),
                ('youtube', models.CharField(max_length=500, verbose_name='Youtube')),
                ('github', models.CharField(max_length=500, verbose_name='Github')),
                ('website', models.CharField(max_length=500, verbose_name='Web Site')),
            ],
        ),
    ]
