# Generated by Django 3.2.6 on 2021-08-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='image',
            field=models.ImageField(default='article/images/author/default.jpg', upload_to='article/images/author/%Y/%m/%d', verbose_name='Resim'),
        ),
    ]
