# Generated by Django 3.2.6 on 2021-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_alter_writers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='image',
            field=models.ImageField(default='articles/images/author/default.jpg', upload_to='articles/images/author/%Y/%m/%d', verbose_name='Resim'),
        ),
    ]
