# Generated by Django 3.2.6 on 2021-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(default='articles/images/site/default.png', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Logo')),
                ('footer', models.CharField(max_length=150, verbose_name='Site Alt Açıklama')),
                ('facebook', models.CharField(max_length=500, verbose_name='facebook')),
                ('twitter', models.CharField(max_length=500, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=500, verbose_name='İnstagram')),
                ('youtube', models.CharField(max_length=500, verbose_name='Youtube')),
                ('image1', models.ImageField(default='articles/images/site/reklam1.jpg', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Resim(Önerilen:1200x1200)')),
                ('image1Url', models.CharField(max_length=500, verbose_name='Reklam 1 Url Adres')),
                ('image2', models.ImageField(default='articles/images/site/reklam2.jpg', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Resim(Önerilen:300x600)')),
                ('image2Url', models.CharField(max_length=500, verbose_name='Reklam 2 Url Adres')),
                ('image3', models.ImageField(default='articles/images/site/reklam3.jpg', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Resim(Önerilen:728x90)')),
                ('image3Url', models.CharField(max_length=500, verbose_name='Reklam 3 Url Adres')),
                ('available', models.BooleanField(default=False, verbose_name='Bakım Durum')),
            ],
        ),
    ]
