# Generated by Django 3.2.6 on 2021-09-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingModel',
            new_name='Setting',
        ),
    ]
