# Generated by Django 3.2.6 on 2021-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_settingmodel_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='author',
            field=models.CharField(default='safecodecenter', max_length=200, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='setting',
            name='descripton',
            field=models.TextField(default='blog content', max_length=500, verbose_name='Açıklama'),
        ),
    ]
