# Generated by Django 3.2.6 on 2021-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210907_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='title',
            field=models.CharField(default='SafeCodeCenter', max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image1',
            field=models.ImageField(default='articles/images/site/reklam1.jpg', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Resim(Önerilen:300x600)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image2',
            field=models.ImageField(default='articles/images/site/reklam1.jpg', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Resim(Önerilen:728x90)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image3',
            field=models.ImageField(default='articles/images/site/reklam2.jpg', upload_to='articles/images/site/%Y/%m/%d', verbose_name='Resim(Önerilen:728x90)'),
        ),
    ]
