# Generated by Django 3.2.6 on 2022-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210907_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='Logo',
            field=models.ImageField(default='static/upload/site/default.png', upload_to='static/upload/site/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image1',
            field=models.ImageField(default='static/upload/site/reklam1.jpg', upload_to='static/upload/site/%Y/%m/%d', verbose_name='Resim(Önerilen:300x600)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image2',
            field=models.ImageField(default='static/upload/site/reklam1.jpg', upload_to='static/upload/site/%Y/%m/%d', verbose_name='Resim(Önerilen:728x90)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image3',
            field=models.ImageField(default='static/upload/site/reklam2.jpg', upload_to='static/upload/site/%Y/%m/%d', verbose_name='Resim(Önerilen:728x90)'),
        ),
    ]
