# Generated by Django 3.2.6 on 2022-09-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20220808_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='kvkk',
            field=models.FileField(null=True, upload_to='static/upload/kvkk/%Y/%m/%d', verbose_name='KVKK PDF'),
        ),
        migrations.AddField(
            model_name='setting',
            name='term_of_use',
            field=models.FileField(null=True, upload_to='static/upload/term_of_use/%Y/%m/%d', verbose_name='Term Of Use PDF'),
        ),
    ]
