# Generated by Django 3.2.6 on 2022-09-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20220915_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='author',
            field=models.CharField(default='Siberatay', max_length=200, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(default='Siberatay', max_length=50, verbose_name='Başlık'),
        ),
    ]
