# Generated by Django 3.2.6 on 2022-10-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20220916_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': 'Ayar Listesi'},
        ),
    ]
